// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI-HSgUbnUTdklg_3JwVAbH_GSWywH_yE',
    appId: '1:901984460055:web:3e25da9f6b4acf3ce3eb52',
    messagingSenderId: '901984460055',
    projectId: 'doclink-72af0',
    authDomain: 'doclink-72af0.firebaseapp.com',
    storageBucket: 'doclink-72af0.firebasestorage.app',
    measurementId: 'G-QW88JG394X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYc0cZg2mQ6L39kyyRLSh0lyizrz-vVz8',
    appId: '1:901984460055:android:5de3462010ea17e7e3eb52',
    messagingSenderId: '901984460055',
    projectId: 'doclink-72af0',
    storageBucket: 'doclink-72af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7twNeGOwFO-DcnUXlJyPsENVtnvO3ZWU',
    appId: '1:901984460055:ios:3c02513c246c22f5e3eb52',
    messagingSenderId: '901984460055',
    projectId: 'doclink-72af0',
    storageBucket: 'doclink-72af0.firebasestorage.app',
    iosBundleId: 'com.example.kodoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7twNeGOwFO-DcnUXlJyPsENVtnvO3ZWU',
    appId: '1:901984460055:ios:3c02513c246c22f5e3eb52',
    messagingSenderId: '901984460055',
    projectId: 'doclink-72af0',
    storageBucket: 'doclink-72af0.firebasestorage.app',
    iosBundleId: 'com.example.kodoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI-HSgUbnUTdklg_3JwVAbH_GSWywH_yE',
    appId: '1:901984460055:web:6f4d8822589ab0bae3eb52',
    messagingSenderId: '901984460055',
    projectId: 'doclink-72af0',
    authDomain: 'doclink-72af0.firebaseapp.com',
    storageBucket: 'doclink-72af0.firebasestorage.app',
    measurementId: 'G-DZ8DN3E5SR',
  );
}
